---
title: 4
author: Truong, testfran, Ilya
output: pdf_document
---

## Aufgabe 1
a.
\begin{verbatim}
WITH RECURSIVE OberGeo(gid. gname, gparent)
AS (
    (SELECT * FROM hierachie
    WHERE id IN (SELECT parent FROM hierarchie WHERE name ='Geo-Datenbanken'))
UNION
    (SELECT hierarchie.* FROM OberGeo, hierarchie
    WHERE OberGeo.gparent = hierarchie.id)
)
SELECT * FROM OberGeo;
\end{verbatim}

b.
\begin{verbatim}
WITH RECURSIVE Tree(rid, rname, rparent)
AS (
    (SELECT * FROM hierachie
    WHERE name = 'Datenbanksysteme I')
UNION
    (SELECT hierachie.* FROM Tree, hierachie
    WHERE Tree.rparent = hierachie.id)
)
SELECT count(*) from Tree;
\end{verbatim}

c.
\begin{verbatim}
SELECT count(*) - 1
FROM hierachie
WHERE parent IN (SELECT parent FROM hierachie
                 WHERE name = 'Grafikprogrammierung II');
\end{verbatim}

d.
\begin{verbatim}
WITH RECURSIVE UnterHaupt(rid, rname, rparent)
AS (
    (SELECT * FROM hierachie
    WHERE name = 'Hauptstudium')
UNION
    (SELECT hierachie.* FROM UnterHaupt, hierachie
    WHERE hierachie.parent = UnterHaupt.rid)
)
SELECT * FROM UnterHaupt
WHERE rname LIKE 'S%';
\end{verbatim}

\pagebreak

## Aufgabe 2
a.
\begin{verbatim}
UPDATE GEHALT
SET jahresgehalt = CASE WHEN jahresgehalt > 70000 THEN jahresgehalt - 2000
                        ELSE jahresgehalt * 1.05
                    END CASE;
\end{verbatim}

b.
\begin{verbatim}
UPDATE GEHALT
SET bonus = bonus + 10000
WHERE name LIKE 'M%';
\end{verbatim}

## Aufgabe 3
a.
\begin{verbatim}
SELECT *
FROM GEHALT G
WHERE jahresgehalt >= ALL(SELECT jahresgehalt FROM GEHALT
                        WHERE G.mitarbeiter_id = mitarbeiter_id);
\end{verbatim}

b.
\begin{verbatim}
SELECT GEHALT.*
FROM GEHALT, (SELECT abteilung, avg(jahresgehalt) as AVGGehalt
              FROM GEHALT GROUP BY abteilung) T
WHERE GEHALT.abteilung = T.abteilung AND jahresgehalt > T.AVGGehalt;
\end{verbatim}

c.
\begin{verbatim}
SELECT * FROM GEHALT
WHERE abteilung IN (
    SELECT abteilung, sum(bonus)
    FROM GEHALT
    GROUP BY abteilung
    HAVING sum(bonus) > (SELECT sum(bonus)/count(distinct abteilung) FROM GEHALT));
\end{verbatim}
