---
title: Abgabe 3
author: Truong, testfran, Zykov
output: pdf_document
---

# Aufgabe 1

a.

\begin{center}
\begin{tabular}{|c|c|c|}
\hline
A & B & C \\ \hline
a & 5 & 5 \\ \hline
b & 2 & 8 \\ \hline
b & 3 & 7 \\ \hline
k & 4 & 3 \\ \hline
l & 1 & 3 \\ \hline
\end{tabular}
\end{center}

b.
    1.

   $(R \uplus S) - T = (R-T) \uplus (S-T)$

   Summenvereinigung gilt nicht fUEr Multimengen

    $R =$ {2,4,6,6,6}

    $S =$ {4,6,6}

    $T =$ {6}

   $(${2,4,6} $\uplus$ {4,6,6}) - {6}

   $=$ {2,4,4,6,6,6} $-$ {6}

   $=$ {2,4,4,6,6}

   Aber $(${2,4,6} $-$ {6}$)\uplus(${4,6,6} $-$ {6}$)$

   $=$ {2,4} $\uplus$ {4,6}

   $=$ {2,4,6,6}

    2.

   $(R\cup_{max}S)-T$

   $=$ {$t | (t \in R \vee t \in S \vee t \in T) \wedge t[V] = max(R[V], S[V]) - T[V]$}

   $=$ {$t | (t \in R \vee t \in S \vee t \in T) \wedge t[V] = max(R[V] - T[V],S[V] - T[V])$}

   $=$ {$t | (t \in R \vee t \in T) \wedge t[V] = R[V] - T[V]$}

   $\cup_{max}$ {$k | (k\in S \vee k \in T) \wedge k[V] = S[V] - T[V]$}

   $= (R-T)\cup_{max}(S-T)$

# Aufgabe 2

a.
\begin{verbatim}
CREATE TABLE Teil (
    TNr int primary key,
    TName varchar(40) not null,
    Farbe varchar(20) default 'blau',
    Gewicht numeric(7,2) not null
    );
\end{verbatim}

b.
\begin{verbatim}
ALTER TABLE Teil ADD Produktionsdauer int not null;
\end{verbatim}

c.
\begin{verbatim}
INSERT INTO Teil VALUES
    (1, 'A', 'grUEn', 5.00, 2'),
    (2, 'B', 'weiSS', 3.00, 3'),
    (3, 'C', 'schwarz', 2.00, 4');
\end{verbatim}

d.
\begin{verbatim}
ALTER TABLE Teil DROP COLUMN Produktionsdauer;
\end{verbatim}

# Aufgabe 3

a.
\begin{verbatim}
SELECT (LNr, TNr, PNr, (Menge * Gewicht) as gesamt_gewicht)
FROM Lieferung NATURAL INNER JOIN Teil;
\end{verbatim}

b.
\begin{verbatim}
SELECT sum(Menge) AS Anzahlteile
FROM Teil NATURAL INNER JOIN Lieferung
WHERE Farbe = 'rot'
GROUP BY Anzahlteile;
\end{verbatim}

# Aufgabe 4

a.
\begin{verbatim}
SELECT TName
FROM Teil
WHERE Farbe = 'blau' and Gewicht BETWEEN 10 AND 50;
\end{verbatim}

b.
\begin{verbatim}
SELECT DISTINCT TName
FROM Teil NATURAL INNER JOIN Lieferung;
\end{verbatim}

c.
\begin{verbatim}
SELECT PName
FROM Projekt EXCEPT (
    SELECT PName
    FROM Projekt NATURAL INNER JOIN Lieferung);
\end{verbatim}

d.
\begin{verbatim}
SELECT LName, avg(Menge) AS Durchschnitt
FROM Lieferant NATURAL INNER JOIN Lieferung
GROUP BY LName, Durchschnitt;
\end{verbatim}

e.
\begin{verbatim}
SELECT DISTINCT PName
FROM Projekt
EXCEPT (SELECT DISTINCT PName
        FROM (Projekt NATURAL INNER JOIN Lieferung) NATURAL INNER JOIN Teil
        WHERE Farbe = 'gelb';
        )
\end{verbatim}
